blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/RooCodeInc/Roo-Code/discussions/categories/feature-requests
      about: Share and vote on feature requests for Roo Code
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=tne-ai.tne-code&ssr=false#review-details
      about: Enjoying Compass? Leave a review here!
